export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const GOOGLE_LOGIN_DETAIL_ACTION = "GOOGLE_LOGIN_DETAIL_ACTION";

export const FLIGHT_LIST_START = "FLIGHT_LIST_START";
export const FLIGHT_LIST_SUCCESS = "FLIGHT_LIST_SUCCESS";
export const FLIGHT_LIST_FAIL = "FLIGHT_LIST_FAIL";

export const FETCH_PASSENGER_DETAILS_START = "FETCH_PASSENGER_DETAILS_START";
export const FETCH_PASSENGER_DETAILS_SUCCESS =
  "FETCH_PASSENGER_DETAILS_SUCCESS";
export const FETCH_PASSENGER_DETAILS_FAIL = "FETCH_PASSENGER_DETAILS_FAIL";

export const FILTER_PASSENGER_DETAILS = "FILTER_PASSENGER_DETAILS";

export const FETCH_SEAT_DETAILS_START = "FETCH_SEAT_DETAILS_START";
export const FETCH_SEAT_DETAILS_SUCCESS = "FETCH_SEAT_DETAILS_SUCCESS";
export const FETCH_SEAT_DETAILS_FAIL = "FETCH_SEAT_DETAILS_FAIL";

export const UPDATE_SEAT_IN_PASSENGER_DETAILS_START =
  "UPDATE_SEAT_IN_PASSENGER_DETAILS_START";
export const UPDATE_SEAT_IN_PASSENGER_DETAILS_SUCCESS =
  "UPDATE_SEAT_IN_PASSENGER_DETAILS_SUCCESS";
export const UPDATE_SEAT_IN_PASSENGER_DETAILS_FAIL =
  "UPDATE_SEAT_IN_PASSENGER_DETAILS_FAIL";

export const UPDATE_SEAT_START = "UPDATE_SEAT_START";
export const UPDATE_SEAT_SUCCESS = "UPDATE_SEAT_SUCCESS";
export const UPDATE_SEAT_FAIL = "UPDATE_SEAT_FAIL";

export const FLIGHT_DETAILS_START = "FLIGHT_DETAILS_START";
export const FLIGHT_DETAILS_SUCCESS = "FLIGHT_DETAILS_SUCCESS";
export const FLIGHT_DETAILS_FAIL = "FLIGHT_DETAILS_FAIL";

export const UPDATE_PASSENGER_MEAL_DETAILS_START =
  "UPDATE_PASSENGER_MEAL_DETAILS_START";
export const UPDATE_PASSENGER_MEAL_DETAILS_SUCCESS =
  "UPDATE_PASSENGER_MEAL_DETAILS_SUCCESS";
export const UPDATE_PASSENGER_MEAL_DETAILS_FAIL =
  "UPDATE_PASSENGER_MEAL_DETAILS_FAIL";

export const UPDATE_PASSENGER_ANCILLARY_DETAILS_START =
  "UPDATE_PASSENGER_ANCILLARY_DETAILS_START";
export const UPDATE_PASSENGER_ANCILLARY_DETAILS_SUCCESS =
  "UPDATE_PASSENGER_ANCILLARY_DETAILS_SUCCESS";
export const UPDATE_PASSENGER_ANCILLARY_DETAILS_FAIL =
  "UPDATE_PASSENGER_ANCILLARY_DETAILS_FAIL";

export const UPDATE_PASSENGER_SHOP_DETAILS_START =
  "UPDATE_PASSENGER_MEAL_SHOP_START";
export const UPDATE_PASSENGER_SHOP_DETAILS_SUCCESS =
  "UPDATE_PASSENGER_MEAL_SHOP_SUCCESS";
export const UPDATE_PASSENGER_SHOP_DETAILS_FAIL =
  "UPDATE_PASSENGER_MEAL_SHOP_FAIL";

export const UPDATE_FLIGHT_SHOP_DETAILS_START = "UPDATE_FLIGHT_MEAL_SHOP_START";
export const UPDATE_FLIGHT_SHOP_DETAILS_SUCCESS =
  "UPDATE_FLIGHT_MEAL_SHOP_SUCCESS";
export const UPDATE_FLIGHT_SHOP_DETAILS_FAIL = "UPDATE_FLIGHT_MEAL_SHOP_FAIL";

export const UPDATE_FLIGHT_ANCILLARY_DETAILS_START =
  "UPDATE_FLIGHT_ANCILLARY_DETAILS_START";
export const UPDATE_FLIGHT_ANCILLARY_DETAILS_SUCCESS =
  "UPDATE_FLIGHT_ANCILLARY_DETAILS_SUCCESS";
export const UPDATE_FLIGHT_ANCILLARY_DETAILS_FAIL =
  "UPDATE_FLIGHT_ANCILLARY_DETAILS_FAIL";

export const UPDATE_FLIGHT_MEAL_DETAILS_START =
  "UPDATE_FLIGHT_MEAL_DETAILS_START";
export const UPDATE_FLIGHT_MEAL_DETAILS_SUCCESS =
  "UPDATE_FLIGHT_MEAL_DETAILS_SUCCESS";
export const UPDATE_FLIGHT_MEAL_DETAILS_FAIL =
  "UPDATE_FLIGHT_MEAL_DETAILS_FAIL";

export const UPDATE_PASSENGER_PERSONAL_INFO_START =
  "UPDATE_PASSENGER_PERSONAL_INFO_START";
export const UPDATE_PASSENGER_PERSONAL_INFO_SUCCESS =
  "UPDATE_PASSENGER_PERSONAL_INFO_SUCCESS";
export const UPDATE_PASSENGER_PERSONAL_INFO_FAIL =
  "UPDATE_PASSENGER_PERSONAL_INFO_FAIL";

export const ADD_PASSENGER_START = "ADD_PASSENGER_START";
export const ADD_PASSENGER_SUCCESS = "ADD_PASSENGER_SUCCESS";
export const ADD_PASSENGER_FAIL = "ADD_PASSENGER_FAIL";
